FROM python:3.6

WORKDIR /usr/src/app

RUN git clone https://github.com/ZhuangweiKang/pycollectdsubscriber.git fecbench-server-docker/pycollector

COPY requirement.txt ./
RUN pip3 install --no-cache-dir -r requirement.txt

COPY . .

CMD /bin/bash
